-- AlterTable
ALTER TABLE "User" ALTER COLUMN "password" SET DATA TYPE TEXT,
ALTER COLUMN "email_id" SET DATA TYPE TEXT,
ALTER COLUMN "name" SET DATA TYPE TEXT,
ALTER COLUMN "contact_number" SET DATA TYPE TEXT,
ALTER COLUMN "alternate_contact_number" SET DATA TYPE TEXT,
ALTER COLUMN "highest_qualification" SET DATA TYPE TEXT,
ALTER COLUMN "status" SET DEFAULT true,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);
