-- AlterTable
ALTER TABLE "User" ALTER COLUMN "password" SET DATA TYPE VARCHAR,
ALTER COLUMN "email_id" SET DATA TYPE VARCHAR,
ALTER COLUMN "name" SET DATA TYPE VARCHAR,
ALTER COLUMN "contact_number" SET DATA TYPE VARCHAR,
ALTER COLUMN "alternate_contact_number" SET DATA TYPE VARCHAR,
ALTER COLUMN "highest_qualification" SET DATA TYPE VARCHAR,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;
